[tool.ruff]
exclude = [
  ".git",
  "venv",
  "node_modules",
  "site-packages"
]

line-length = 176
indent-width = 4

[tool.ruff.lint]
# ruff rulesets
select = [
  "A",
  "E",
  "F",
  "N",
  "FAST",
  "W",
]
ignore = []
fixable = ["ALL"]
preview = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.isort]
case-sensitive = true

[tool.pyright]
typeCheckingMode = "off"
